{
  "regions": ["hnd1"],
  "functions": {
    "php/*.php": {
      "runtime": "vercel-php@0.3.1"
    }
  },
  "routes": [
    { "src": "/(.*)", "dest": "/$1" },
    { "handle": "filesystem" },
    { "src": "/.*", "dest": "/404.html" }
  ]
}